#!/bin/bash

DIR="$(pwd)"
JAVA_11_HOME="$(readlink -f "$DIR/openjdk-11")"
JAVA_8_HOME="$(readlink -f "$DIR/openjdk-8")"
export ANDROID_SDK_ROOT="$(readlink -f "$DIR/android-sdk")"

if [ ! -e "$JAVA_8_HOME/bin/java" ]; then
	if [ ! -e "openjdk-8.tar.gz" ]; then
		echo "Donwloading openjdk-8"
		wget "https://github.com/CnC-Robert/revanced-cli-script/releases/download/java-androidsdk/openjdk-8.tar.gz"
	fi
	echo "Extracting openjdk-8.tar.gz"
	tar xzf "openjdk-8.tar.gz"
fi

if [ ! -e "$JAVA_11_HOME/bin/java" ]; then
	if [ ! -e "openjdk-11.tar.gz" ]; then
		echo "Donwloading openjdk-11"
		echo
		wget "https://github.com/CnC-Robert/revanced-cli-script/releases/download/java-androidsdk/openjdk-11.tar.gz"
	fi
	echo "Extracting openjdk-11.tar.gz"
	tar xzf "openjdk-11.tar.gz"
fi

if [ ! -e "$ANDROID_SDK_ROOT" ]; then
	if [ ! -e "android-sdk.tar.gz" ]; then
		echo "Donwloading Android SDK"
		echo
		wget "https://github.com/CnC-Robert/revanced-cli-script/releases/download/java-androidsdk/android-sdk.tar.gz"
	fi
	echo "Extracting android-sdk.tar.gz"
	tar xzf "android-sdk.tar.gz"
fi

if [ ! -e "$DIR/build/youtube.apk" ]; then
	echo "Error, ./build/youtube.apk not found"
	exit 1
fi

export JAVA_HOME="$JAVA_8_HOME"

echo
git clone https://github.com/revanced/revanced-patcher
cd revanced-patcher
git checkout dev
chmod +x ./gradlew

./gradlew publish
RETURN_CODE="$?"

if [ ! $RETURN_CODE == 0 ]; then
	echo Build failed
	exit 1
fi

cd ..

echo
git clone https://github.com/revanced/revanced-patches
cd revanced-patches
git checkout dev
chmod +x ./gradlew

./gradlew publish
RETURN_CODE="$?"

if [ ! $RETURN_CODE == 0 ]; then
	echo Build failed
	exit 1
fi

cd ..

echo
git clone https://github.com/revanced/revanced-cli
cd revanced-cli
REMOVE="if (clean) outputFile.delete()"
sed -i "/$REMOVE/d" src/main/kotlin/app/revanced/cli/MainCommand.kt
chmod +x ./gradlew

./gradlew build
RETURN_CODE="$?"

if [ ! $RETURN_CODE == 0 ]; then
	echo Build failed
	exit 1
fi

cd ..

export JAVA_HOME="$JAVA_11_HOME"

echo
git clone https://github.com/revanced/revanced-integrations
cd revanced-integrations
chmod +x ./gradlew

./gradlew build
RETURN_CODE="$?"

if [ ! $RETURN_CODE == 0 ]; then
	echo Build failed
	exit 1
fi

export JAVA_HOME="$JAVA_8_HOME"

cd ..

cp revanced-cli/build/libs/revanced-cli-*-all.jar build/revanced-cli.jar
cp revanced-integrations/app/build/outputs/apk/release/*.apk build/integrations.apk
rsync -av --exclude="*-javadoc.jar" --exclude="*-sources.jar" "revanced-patches/build/libs/" "build/revanced-patches/"
rsync -av --exclude="*-javadoc.jar" --exclude="*-sources.jar" "revanced-patcher/build/libs/" "build/revanced-patcher/"

cd build

"$DIR/openjdk-8/bin/java" -jar revanced-cli.jar -a youtube.apk -c cache -m integrations.apk -o revanced.apk -p revanced-patches/revanced-patches*.jar -r -t temp

cp "$DIR/build/revanced.apk" "$DIR/revanced.apk"

exit 0
